---

- name: Power Control 
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    cluster: "{{ vcenter_cluster }}"
    name: "{{ hostname }}"
    state: "{{ vm_state }}"
  delegate_to: localhost

- name: Wait 300 seconds for remote system to be available, but only start checking after 30 seconds
  wait_for_connection:
    delay: 30
    timeout: 300
