---

- hosts: nodes:lb:new_nodes
  gather_facts: false
  serial: "100%"
  roles:
    - vmware_create_vm

- hosts: nodes:new_nodes
  gather_facts: false
  serial: "100%"
  roles:
    - vmware_add_disk

- hosts: nodes:lb:new_nodes
  gather_facts: false
  serial: "100%"
  tasks:
  - include_role:
       name: vm_power
    vars:
      vm_state: 'restarted'

